version: "3"
services:
  web:
    build: ./
    image: skobara/river_discharge
    container_name: river_discharge
    restart: always
    ports:
      - "8004:3000"
    volumes:
      - "./:/usr/src/app"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:geo.gcoos.org;PathPrefix:/river_discharge"
      - "traefik.port=3000"
      - "traefik.docker.network=geo_net"
    networks:
      - geo_net

networks:
  geo_net:
    external: true
